version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: production
  ignore:
  - dependency-name: terser
    versions:
    - 5.6.0
    - 5.6.1
  - dependency-name: svgo
    versions:
    - 2.0.0
    - 2.0.1
    - 2.0.3
    - 2.1.0
    - 2.2.0
    - 2.2.1
    - 2.2.2
  - dependency-name: htmlparser2
    versions:
    - 6.0.1
